name: upsen_tablet_get
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  #State management
  get: ^4.7.2

  #Camera & ML
  camera: ^0.11.2
  image: ^4.5.4
  google_mlkit_face_detection: ^0.13.1
  tflite_flutter: ^0.11.0
  flutter_svg: ^2.2.0

  #Database
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1

  #Network
  dio: ^5.9.0

  #utilities
  intl: ^0.20.2
  permission_handler: ^12.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

assets:
  - assets/
  - assets/images/
  - assets/models/

fonts:
  - family: Inter
    fonts:
      - asset: fonts/Inter-Regular.ttf
      - asset: fonts/Inter-Bold.ttf
        weight: 700
