name: upsen_tablet_get
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  cached_network_image: ^3.4.1
  camera: ^0.11.2
  connectivity_plus: ^6.1.5
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  get: ^4.7.2
  google_mlkit_face_detection: ^0.13.1
  image: ^4.5.4
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  sqflite: ^2.4.2
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
